//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_HoaDon_PhieuThue", "PhieuThue", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.PhieuThue), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.HoaDon), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_KhachHang_LoaiKhachHang", "LoaiKhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.LoaiKhachHang), "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.KhachHang), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_NhanVien_LoaiNhanVien", "LoaiNhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.LoaiNhanVien), "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.NhanVien), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.TinhTrangLoaiPhong), "LoaiPhong", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.LoaiPhong), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_Phong_LoaiPhong", "LoaiPhong", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.LoaiPhong), "Phong", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.Phong), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_PhieuThue_NhanVien", "NhanVien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.NhanVien), "PhieuThue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.PhieuThue), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_PhieuThue_Phong", "Phong", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.Phong), "PhieuThue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.PhieuThue), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_PhieuThue_TinhTrangPT", "TinhTrangPT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DTOLayer.TinhTrangPT), "PhieuThue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.PhieuThue), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "FK_Phong_TinhTrangPhong", "TinhTrangPhong", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DTOLayer.TinhTrangPhong), "Phong", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.Phong), true)]
[assembly: EdmRelationshipAttribute("QuanLyKhachSanModel", "CTPhieuThue", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.KhachHang), "PhieuThue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DTOLayer.PhieuThue))]

#endregion

namespace DTOLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuanLyKhachSanEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuanLyKhachSanEntities object using the connection string found in the 'QuanLyKhachSanEntities' section of the application configuration file.
        /// </summary>
        public QuanLyKhachSanEntities() : base("name=QuanLyKhachSanEntities", "QuanLyKhachSanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyKhachSanEntities object.
        /// </summary>
        public QuanLyKhachSanEntities(string connectionString) : base(connectionString, "QuanLyKhachSanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLyKhachSanEntities object.
        /// </summary>
        public QuanLyKhachSanEntities(EntityConnection connection) : base(connection, "QuanLyKhachSanEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDons
        {
            get
            {
                if ((_HoaDons == null))
                {
                    _HoaDons = base.CreateObjectSet<HoaDon>("HoaDons");
                }
                return _HoaDons;
            }
        }
        private ObjectSet<HoaDon> _HoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiKhachHang> LoaiKhachHangs
        {
            get
            {
                if ((_LoaiKhachHangs == null))
                {
                    _LoaiKhachHangs = base.CreateObjectSet<LoaiKhachHang>("LoaiKhachHangs");
                }
                return _LoaiKhachHangs;
            }
        }
        private ObjectSet<LoaiKhachHang> _LoaiKhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiNhanVien> LoaiNhanViens
        {
            get
            {
                if ((_LoaiNhanViens == null))
                {
                    _LoaiNhanViens = base.CreateObjectSet<LoaiNhanVien>("LoaiNhanViens");
                }
                return _LoaiNhanViens;
            }
        }
        private ObjectSet<LoaiNhanVien> _LoaiNhanViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiPhong> LoaiPhongs
        {
            get
            {
                if ((_LoaiPhongs == null))
                {
                    _LoaiPhongs = base.CreateObjectSet<LoaiPhong>("LoaiPhongs");
                }
                return _LoaiPhongs;
            }
        }
        private ObjectSet<LoaiPhong> _LoaiPhongs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NhanVien> NhanViens
        {
            get
            {
                if ((_NhanViens == null))
                {
                    _NhanViens = base.CreateObjectSet<NhanVien>("NhanViens");
                }
                return _NhanViens;
            }
        }
        private ObjectSet<NhanVien> _NhanViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhieuThue> PhieuThues
        {
            get
            {
                if ((_PhieuThues == null))
                {
                    _PhieuThues = base.CreateObjectSet<PhieuThue>("PhieuThues");
                }
                return _PhieuThues;
            }
        }
        private ObjectSet<PhieuThue> _PhieuThues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Phong> Phongs
        {
            get
            {
                if ((_Phongs == null))
                {
                    _Phongs = base.CreateObjectSet<Phong>("Phongs");
                }
                return _Phongs;
            }
        }
        private ObjectSet<Phong> _Phongs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuyDinh> QuyDinhs
        {
            get
            {
                if ((_QuyDinhs == null))
                {
                    _QuyDinhs = base.CreateObjectSet<QuyDinh>("QuyDinhs");
                }
                return _QuyDinhs;
            }
        }
        private ObjectSet<QuyDinh> _QuyDinhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TinhTrangLoaiPhong> TinhTrangLoaiPhongs
        {
            get
            {
                if ((_TinhTrangLoaiPhongs == null))
                {
                    _TinhTrangLoaiPhongs = base.CreateObjectSet<TinhTrangLoaiPhong>("TinhTrangLoaiPhongs");
                }
                return _TinhTrangLoaiPhongs;
            }
        }
        private ObjectSet<TinhTrangLoaiPhong> _TinhTrangLoaiPhongs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TinhTrangPhong> TinhTrangPhongs
        {
            get
            {
                if ((_TinhTrangPhongs == null))
                {
                    _TinhTrangPhongs = base.CreateObjectSet<TinhTrangPhong>("TinhTrangPhongs");
                }
                return _TinhTrangPhongs;
            }
        }
        private ObjectSet<TinhTrangPhong> _TinhTrangPhongs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TinhTrangPT> TinhTrangPTs
        {
            get
            {
                if ((_TinhTrangPTs == null))
                {
                    _TinhTrangPTs = base.CreateObjectSet<TinhTrangPT>("TinhTrangPTs");
                }
                return _TinhTrangPTs;
            }
        }
        private ObjectSet<TinhTrangPT> _TinhTrangPTs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDons(HoaDon hoaDon)
        {
            base.AddObject("HoaDons", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiKhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiKhachHangs(LoaiKhachHang loaiKhachHang)
        {
            base.AddObject("LoaiKhachHangs", loaiKhachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiNhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiNhanViens(LoaiNhanVien loaiNhanVien)
        {
            base.AddObject("LoaiNhanViens", loaiNhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiPhongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiPhongs(LoaiPhong loaiPhong)
        {
            base.AddObject("LoaiPhongs", loaiPhong);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNhanViens(NhanVien nhanVien)
        {
            base.AddObject("NhanViens", nhanVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhieuThues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhieuThues(PhieuThue phieuThue)
        {
            base.AddObject("PhieuThues", phieuThue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhongs(Phong phong)
        {
            base.AddObject("Phongs", phong);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuyDinhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuyDinhs(QuyDinh quyDinh)
        {
            base.AddObject("QuyDinhs", quyDinh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhTrangLoaiPhongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinhTrangLoaiPhongs(TinhTrangLoaiPhong tinhTrangLoaiPhong)
        {
            base.AddObject("TinhTrangLoaiPhongs", tinhTrangLoaiPhong);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhTrangPhongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinhTrangPhongs(TinhTrangPhong tinhTrangPhong)
        {
            base.AddObject("TinhTrangPhongs", tinhTrangPhong);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhTrangPTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTinhTrangPTs(TinhTrangPT tinhTrangPT)
        {
            base.AddObject("TinhTrangPTs", tinhTrangPT);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Phong> spp_dspphong()
        {
            return base.ExecuteFunction<Phong>("spp_dspphong");
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        public ObjectResult<Phong> spp_dspphong(MergeOption mergeOption)
        {
            return base.ExecuteFunction<Phong>("spp_dspphong", mergeOption);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="maHD">Initial value of the MaHD property.</param>
        public static HoaDon CreateHoaDon(global::System.Int32 maHD)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.MaHD = maHD;
            return hoaDon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaHD
        {
            get
            {
                return _MaHD;
            }
            set
            {
                if (_MaHD != value)
                {
                    OnMaHDChanging(value);
                    ReportPropertyChanging("MaHD");
                    _MaHD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaHD");
                    OnMaHDChanged();
                }
            }
        }
        private global::System.Int32 _MaHD;
        partial void OnMaHDChanging(global::System.Int32 value);
        partial void OnMaHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                OnMaNVChanging(value);
                ReportPropertyChanging("MaNV");
                _MaNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaNV");
                OnMaNVChanged();
            }
        }
        private global::System.String _MaNV;
        partial void OnMaNVChanging(global::System.String value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                OnMaKHChanging(value);
                ReportPropertyChanging("MaKH");
                _MaKH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaKH");
                OnMaKHChanged();
            }
        }
        private Nullable<global::System.Int32> _MaKH;
        partial void OnMaKHChanging(Nullable<global::System.Int32> value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayLap
        {
            get
            {
                return _NgayLap;
            }
            set
            {
                OnNgayLapChanging(value);
                ReportPropertyChanging("NgayLap");
                _NgayLap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLap");
                OnNgayLapChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayLap;
        partial void OnNgayLapChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayLapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TriGia
        {
            get
            {
                return _TriGia;
            }
            set
            {
                OnTriGiaChanging(value);
                ReportPropertyChanging("TriGia");
                _TriGia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TriGia");
                OnTriGiaChanged();
            }
        }
        private Nullable<global::System.Double> _TriGia;
        partial void OnTriGiaChanging(Nullable<global::System.Double> value);
        partial void OnTriGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoNgayThue
        {
            get
            {
                return _SoNgayThue;
            }
            set
            {
                OnSoNgayThueChanging(value);
                ReportPropertyChanging("SoNgayThue");
                _SoNgayThue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoNgayThue");
                OnSoNgayThueChanged();
            }
        }
        private Nullable<global::System.Int32> _SoNgayThue;
        partial void OnSoNgayThueChanging(Nullable<global::System.Int32> value);
        partial void OnSoNgayThueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DonGia
        {
            get
            {
                return _DonGia;
            }
            set
            {
                OnDonGiaChanging(value);
                ReportPropertyChanging("DonGia");
                _DonGia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonGia");
                OnDonGiaChanged();
            }
        }
        private Nullable<global::System.Double> _DonGia;
        partial void OnDonGiaChanging(Nullable<global::System.Double> value);
        partial void OnDonGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaPhieuThue
        {
            get
            {
                return _MaPhieuThue;
            }
            set
            {
                OnMaPhieuThueChanging(value);
                ReportPropertyChanging("MaPhieuThue");
                _MaPhieuThue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaPhieuThue");
                OnMaPhieuThueChanged();
            }
        }
        private Nullable<global::System.Int32> _MaPhieuThue;
        partial void OnMaPhieuThueChanging(Nullable<global::System.Int32> value);
        partial void OnMaPhieuThueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_HoaDon_PhieuThue", "PhieuThue")]
        public PhieuThue PhieuThue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuThue>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "PhieuThue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuThue>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "PhieuThue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhieuThue> PhieuThueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuThue>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "PhieuThue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhieuThue>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "PhieuThue", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static KhachHang CreateKhachHang(global::System.Int32 maKH)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKH = maKH;
            return khachHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                if (_MaKH != value)
                {
                    OnMaKHChanging(value);
                    ReportPropertyChanging("MaKH");
                    _MaKH = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaKH");
                    OnMaKHChanged();
                }
            }
        }
        private global::System.Int32 _MaKH;
        partial void OnMaKHChanging(global::System.Int32 value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKH
        {
            get
            {
                return _TenKH;
            }
            set
            {
                OnTenKHChanging(value);
                ReportPropertyChanging("TenKH");
                _TenKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenKH");
                OnTenKHChanged();
            }
        }
        private global::System.String _TenKH;
        partial void OnTenKHChanging(global::System.String value);
        partial void OnTenKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CMND
        {
            get
            {
                return _CMND;
            }
            set
            {
                OnCMNDChanging(value);
                ReportPropertyChanging("CMND");
                _CMND = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CMND");
                OnCMNDChanged();
            }
        }
        private global::System.String _CMND;
        partial void OnCMNDChanging(global::System.String value);
        partial void OnCMNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoaiKH
        {
            get
            {
                return _LoaiKH;
            }
            set
            {
                OnLoaiKHChanging(value);
                ReportPropertyChanging("LoaiKH");
                _LoaiKH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoaiKH");
                OnLoaiKHChanged();
            }
        }
        private Nullable<global::System.Int32> _LoaiKH;
        partial void OnLoaiKHChanging(Nullable<global::System.Int32> value);
        partial void OnLoaiKHChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_KhachHang_LoaiKhachHang", "LoaiKhachHang")]
        public LoaiKhachHang LoaiKhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiKhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "LoaiKhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiKhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "LoaiKhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiKhachHang> LoaiKhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiKhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "LoaiKhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiKhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "LoaiKhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "CTPhieuThue", "PhieuThue")]
        public EntityCollection<PhieuThue> PhieuThues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhieuThue>("QuanLyKhachSanModel.CTPhieuThue", "PhieuThue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhieuThue>("QuanLyKhachSanModel.CTPhieuThue", "PhieuThue", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="LoaiKhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiKhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiKhachHang object.
        /// </summary>
        /// <param name="loaiKH">Initial value of the LoaiKH property.</param>
        public static LoaiKhachHang CreateLoaiKhachHang(global::System.Int32 loaiKH)
        {
            LoaiKhachHang loaiKhachHang = new LoaiKhachHang();
            loaiKhachHang.LoaiKH = loaiKH;
            return loaiKhachHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoaiKH
        {
            get
            {
                return _LoaiKH;
            }
            set
            {
                if (_LoaiKH != value)
                {
                    OnLoaiKHChanging(value);
                    ReportPropertyChanging("LoaiKH");
                    _LoaiKH = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoaiKH");
                    OnLoaiKHChanged();
                }
            }
        }
        private global::System.Int32 _LoaiKH;
        partial void OnLoaiKHChanging(global::System.Int32 value);
        partial void OnLoaiKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiKH
        {
            get
            {
                return _TenLoaiKH;
            }
            set
            {
                OnTenLoaiKHChanging(value);
                ReportPropertyChanging("TenLoaiKH");
                _TenLoaiKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiKH");
                OnTenLoaiKHChanged();
            }
        }
        private global::System.String _TenLoaiKH;
        partial void OnTenLoaiKHChanging(global::System.String value);
        partial void OnTenLoaiKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> HeSo
        {
            get
            {
                return _HeSo;
            }
            set
            {
                OnHeSoChanging(value);
                ReportPropertyChanging("HeSo");
                _HeSo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeSo");
                OnHeSoChanged();
            }
        }
        private Nullable<global::System.Double> _HeSo;
        partial void OnHeSoChanging(Nullable<global::System.Double> value);
        partial void OnHeSoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_KhachHang_LoaiKhachHang", "KhachHang")]
        public EntityCollection<KhachHang> KhachHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KhachHang>("QuanLyKhachSanModel.FK_KhachHang_LoaiKhachHang", "KhachHang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="LoaiNhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiNhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiNhanVien object.
        /// </summary>
        /// <param name="maLoai">Initial value of the MaLoai property.</param>
        public static LoaiNhanVien CreateLoaiNhanVien(global::System.Int32 maLoai)
        {
            LoaiNhanVien loaiNhanVien = new LoaiNhanVien();
            loaiNhanVien.MaLoai = maLoai;
            return loaiNhanVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLoai
        {
            get
            {
                return _MaLoai;
            }
            set
            {
                if (_MaLoai != value)
                {
                    OnMaLoaiChanging(value);
                    ReportPropertyChanging("MaLoai");
                    _MaLoai = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLoai");
                    OnMaLoaiChanged();
                }
            }
        }
        private global::System.Int32 _MaLoai;
        partial void OnMaLoaiChanging(global::System.Int32 value);
        partial void OnMaLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoai
        {
            get
            {
                return _TenLoai;
            }
            set
            {
                OnTenLoaiChanging(value);
                ReportPropertyChanging("TenLoai");
                _TenLoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoai");
                OnTenLoaiChanged();
            }
        }
        private global::System.String _TenLoai;
        partial void OnTenLoaiChanging(global::System.String value);
        partial void OnTenLoaiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_NhanVien_LoaiNhanVien", "NhanVien")]
        public EntityCollection<NhanVien> NhanViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "NhanVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="LoaiPhong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiPhong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiPhong object.
        /// </summary>
        /// <param name="maLoaiPhong">Initial value of the MaLoaiPhong property.</param>
        public static LoaiPhong CreateLoaiPhong(global::System.Int32 maLoaiPhong)
        {
            LoaiPhong loaiPhong = new LoaiPhong();
            loaiPhong.MaLoaiPhong = maLoaiPhong;
            return loaiPhong;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaLoaiPhong
        {
            get
            {
                return _MaLoaiPhong;
            }
            set
            {
                if (_MaLoaiPhong != value)
                {
                    OnMaLoaiPhongChanging(value);
                    ReportPropertyChanging("MaLoaiPhong");
                    _MaLoaiPhong = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaLoaiPhong");
                    OnMaLoaiPhongChanged();
                }
            }
        }
        private global::System.Int32 _MaLoaiPhong;
        partial void OnMaLoaiPhongChanging(global::System.Int32 value);
        partial void OnMaLoaiPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoaiPhong
        {
            get
            {
                return _TenLoaiPhong;
            }
            set
            {
                OnTenLoaiPhongChanging(value);
                ReportPropertyChanging("TenLoaiPhong");
                _TenLoaiPhong = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoaiPhong");
                OnTenLoaiPhongChanged();
            }
        }
        private global::System.String _TenLoaiPhong;
        partial void OnTenLoaiPhongChanging(global::System.String value);
        partial void OnTenLoaiPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DonGia
        {
            get
            {
                return _DonGia;
            }
            set
            {
                OnDonGiaChanging(value);
                ReportPropertyChanging("DonGia");
                _DonGia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonGia");
                OnDonGiaChanged();
            }
        }
        private Nullable<global::System.Double> _DonGia;
        partial void OnDonGiaChanging(Nullable<global::System.Double> value);
        partial void OnDonGiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Int32> _TrangThai;
        partial void OnTrangThaiChanging(Nullable<global::System.Int32> value);
        partial void OnTrangThaiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong")]
        public TinhTrangLoaiPhong TinhTrangLoaiPhong
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangLoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangLoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TinhTrangLoaiPhong> TinhTrangLoaiPhongReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangLoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TinhTrangLoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "TinhTrangLoaiPhong", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_Phong_LoaiPhong", "Phong")]
        public EntityCollection<Phong> Phongs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Phong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "Phong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Phong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "Phong", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="NhanVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NhanVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NhanVien object.
        /// </summary>
        /// <param name="maNV">Initial value of the MaNV property.</param>
        public static NhanVien CreateNhanVien(global::System.String maNV)
        {
            NhanVien nhanVien = new NhanVien();
            nhanVien.MaNV = maNV;
            return nhanVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                if (_MaNV != value)
                {
                    OnMaNVChanging(value);
                    ReportPropertyChanging("MaNV");
                    _MaNV = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaNV");
                    OnMaNVChanged();
                }
            }
        }
        private global::System.String _MaNV;
        partial void OnMaNVChanging(global::System.String value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CMND
        {
            get
            {
                return _CMND;
            }
            set
            {
                OnCMNDChanging(value);
                ReportPropertyChanging("CMND");
                _CMND = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CMND");
                OnCMNDChanged();
            }
        }
        private global::System.String _CMND;
        partial void OnCMNDChanging(global::System.String value);
        partial void OnCMNDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDT
        {
            get
            {
                return _SDT;
            }
            set
            {
                OnSDTChanging(value);
                ReportPropertyChanging("SDT");
                _SDT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SDT");
                OnSDTChanged();
            }
        }
        private global::System.String _SDT;
        partial void OnSDTChanging(global::System.String value);
        partial void OnSDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TinhTrang
        {
            get
            {
                return _TinhTrang;
            }
            set
            {
                OnTinhTrangChanging(value);
                ReportPropertyChanging("TinhTrang");
                _TinhTrang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TinhTrang");
                OnTinhTrangChanged();
            }
        }
        private Nullable<global::System.Int32> _TinhTrang;
        partial void OnTinhTrangChanging(Nullable<global::System.Int32> value);
        partial void OnTinhTrangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoaiNV
        {
            get
            {
                return _LoaiNV;
            }
            set
            {
                OnLoaiNVChanging(value);
                ReportPropertyChanging("LoaiNV");
                _LoaiNV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoaiNV");
                OnLoaiNVChanged();
            }
        }
        private Nullable<global::System.Int32> _LoaiNV;
        partial void OnLoaiNVChanging(Nullable<global::System.Int32> value);
        partial void OnLoaiNVChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_NhanVien_LoaiNhanVien", "LoaiNhanVien")]
        public LoaiNhanVien LoaiNhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiNhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "LoaiNhanVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiNhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "LoaiNhanVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiNhanVien> LoaiNhanVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiNhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "LoaiNhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiNhanVien>("QuanLyKhachSanModel.FK_NhanVien_LoaiNhanVien", "LoaiNhanVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_NhanVien", "PhieuThue")]
        public EntityCollection<PhieuThue> PhieuThues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "PhieuThue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "PhieuThue", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="PhieuThue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhieuThue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhieuThue object.
        /// </summary>
        /// <param name="maPhieu">Initial value of the MaPhieu property.</param>
        public static PhieuThue CreatePhieuThue(global::System.Int32 maPhieu)
        {
            PhieuThue phieuThue = new PhieuThue();
            phieuThue.MaPhieu = maPhieu;
            return phieuThue;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaPhieu
        {
            get
            {
                return _MaPhieu;
            }
            set
            {
                if (_MaPhieu != value)
                {
                    OnMaPhieuChanging(value);
                    ReportPropertyChanging("MaPhieu");
                    _MaPhieu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaPhieu");
                    OnMaPhieuChanged();
                }
            }
        }
        private global::System.Int32 _MaPhieu;
        partial void OnMaPhieuChanging(global::System.Int32 value);
        partial void OnMaPhieuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayThue
        {
            get
            {
                return _NgayThue;
            }
            set
            {
                OnNgayThueChanging(value);
                ReportPropertyChanging("NgayThue");
                _NgayThue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayThue");
                OnNgayThueChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayThue;
        partial void OnNgayThueChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayThueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaPhong
        {
            get
            {
                return _MaPhong;
            }
            set
            {
                OnMaPhongChanging(value);
                ReportPropertyChanging("MaPhong");
                _MaPhong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaPhong");
                OnMaPhongChanged();
            }
        }
        private Nullable<global::System.Int32> _MaPhong;
        partial void OnMaPhongChanging(Nullable<global::System.Int32> value);
        partial void OnMaPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaNV
        {
            get
            {
                return _MaNV;
            }
            set
            {
                OnMaNVChanging(value);
                ReportPropertyChanging("MaNV");
                _MaNV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaNV");
                OnMaNVChanged();
            }
        }
        private global::System.String _MaNV;
        partial void OnMaNVChanging(global::System.String value);
        partial void OnMaNVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoNguoi
        {
            get
            {
                return _SoNguoi;
            }
            set
            {
                OnSoNguoiChanging(value);
                ReportPropertyChanging("SoNguoi");
                _SoNguoi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoNguoi");
                OnSoNguoiChanged();
            }
        }
        private Nullable<global::System.Int32> _SoNguoi;
        partial void OnSoNguoiChanging(Nullable<global::System.Int32> value);
        partial void OnSoNguoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TinhTrang
        {
            get
            {
                return _TinhTrang;
            }
            set
            {
                OnTinhTrangChanging(value);
                ReportPropertyChanging("TinhTrang");
                _TinhTrang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TinhTrang");
                OnTinhTrangChanged();
            }
        }
        private Nullable<global::System.Int32> _TinhTrang;
        partial void OnTinhTrangChanging(Nullable<global::System.Int32> value);
        partial void OnTinhTrangChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_HoaDon_PhieuThue", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("QuanLyKhachSanModel.FK_HoaDon_PhieuThue", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_NhanVien", "NhanVien")]
        public NhanVien NhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "NhanVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "NhanVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NhanVien> NhanVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NhanVien>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "NhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NhanVien>("QuanLyKhachSanModel.FK_PhieuThue_NhanVien", "NhanVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_Phong", "Phong")]
        public Phong Phong
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phong>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "Phong").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phong>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "Phong").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Phong> PhongReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phong>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "Phong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Phong>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "Phong", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_TinhTrangPT", "TinhTrangPT")]
        public TinhTrangPT TinhTrangPT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPT>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "TinhTrangPT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPT>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "TinhTrangPT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TinhTrangPT> TinhTrangPTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPT>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "TinhTrangPT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TinhTrangPT>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "TinhTrangPT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "CTPhieuThue", "KhachHang")]
        public EntityCollection<KhachHang> KhachHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KhachHang>("QuanLyKhachSanModel.CTPhieuThue", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KhachHang>("QuanLyKhachSanModel.CTPhieuThue", "KhachHang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="Phong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Phong object.
        /// </summary>
        /// <param name="maPhong">Initial value of the MaPhong property.</param>
        /// <param name="tinhTrang">Initial value of the TinhTrang property.</param>
        public static Phong CreatePhong(global::System.Int32 maPhong, global::System.Int32 tinhTrang)
        {
            Phong phong = new Phong();
            phong.MaPhong = maPhong;
            phong.TinhTrang = tinhTrang;
            return phong;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaPhong
        {
            get
            {
                return _MaPhong;
            }
            set
            {
                if (_MaPhong != value)
                {
                    OnMaPhongChanging(value);
                    ReportPropertyChanging("MaPhong");
                    _MaPhong = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaPhong");
                    OnMaPhongChanged();
                }
            }
        }
        private global::System.Int32 _MaPhong;
        partial void OnMaPhongChanging(global::System.Int32 value);
        partial void OnMaPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenPhong
        {
            get
            {
                return _TenPhong;
            }
            set
            {
                OnTenPhongChanging(value);
                ReportPropertyChanging("TenPhong");
                _TenPhong = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenPhong");
                OnTenPhongChanged();
            }
        }
        private global::System.String _TenPhong;
        partial void OnTenPhongChanging(global::System.String value);
        partial void OnTenPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LoaiPhong
        {
            get
            {
                return _LoaiPhong;
            }
            set
            {
                OnLoaiPhongChanging(value);
                ReportPropertyChanging("LoaiPhong");
                _LoaiPhong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoaiPhong");
                OnLoaiPhongChanged();
            }
        }
        private Nullable<global::System.Int32> _LoaiPhong;
        partial void OnLoaiPhongChanging(Nullable<global::System.Int32> value);
        partial void OnLoaiPhongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TinhTrang
        {
            get
            {
                return _TinhTrang;
            }
            set
            {
                OnTinhTrangChanging(value);
                ReportPropertyChanging("TinhTrang");
                _TinhTrang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TinhTrang");
                OnTinhTrangChanged();
            }
        }
        private global::System.Int32 _TinhTrang;
        partial void OnTinhTrangChanging(global::System.Int32 value);
        partial void OnTinhTrangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoNguoi
        {
            get
            {
                return _SoNguoi;
            }
            set
            {
                OnSoNguoiChanging(value);
                ReportPropertyChanging("SoNguoi");
                _SoNguoi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoNguoi");
                OnSoNguoiChanged();
            }
        }
        private Nullable<global::System.Int32> _SoNguoi;
        partial void OnSoNguoiChanging(Nullable<global::System.Int32> value);
        partial void OnSoNguoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_Phong_LoaiPhong", "LoaiPhong")]
        public LoaiPhong LoaiPhong1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiPhong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "LoaiPhong").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiPhong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "LoaiPhong").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiPhong> LoaiPhong1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiPhong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "LoaiPhong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiPhong>("QuanLyKhachSanModel.FK_Phong_LoaiPhong", "LoaiPhong", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_Phong", "PhieuThue")]
        public EntityCollection<PhieuThue> PhieuThues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "PhieuThue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_Phong", "PhieuThue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_Phong_TinhTrangPhong", "TinhTrangPhong")]
        public TinhTrangPhong TinhTrangPhong
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPhong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "TinhTrangPhong").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPhong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "TinhTrangPhong").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TinhTrangPhong> TinhTrangPhongReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhTrangPhong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "TinhTrangPhong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TinhTrangPhong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "TinhTrangPhong", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="QuyDinh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuyDinh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuyDinh object.
        /// </summary>
        /// <param name="maQD">Initial value of the MaQD property.</param>
        public static QuyDinh CreateQuyDinh(global::System.Int32 maQD)
        {
            QuyDinh quyDinh = new QuyDinh();
            quyDinh.MaQD = maQD;
            return quyDinh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaQD
        {
            get
            {
                return _MaQD;
            }
            set
            {
                if (_MaQD != value)
                {
                    OnMaQDChanging(value);
                    ReportPropertyChanging("MaQD");
                    _MaQD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaQD");
                    OnMaQDChanged();
                }
            }
        }
        private global::System.Int32 _MaQD;
        partial void OnMaQDChanging(global::System.Int32 value);
        partial void OnMaQDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenQD
        {
            get
            {
                return _TenQD;
            }
            set
            {
                OnTenQDChanging(value);
                ReportPropertyChanging("TenQD");
                _TenQD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenQD");
                OnTenQDChanged();
            }
        }
        private global::System.String _TenQD;
        partial void OnTenQDChanging(global::System.String value);
        partial void OnTenQDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> HeSo
        {
            get
            {
                return _HeSo;
            }
            set
            {
                OnHeSoChanging(value);
                ReportPropertyChanging("HeSo");
                _HeSo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeSo");
                OnHeSoChanged();
            }
        }
        private Nullable<global::System.Double> _HeSo;
        partial void OnHeSoChanging(Nullable<global::System.Double> value);
        partial void OnHeSoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="TinhTrangLoaiPhong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinhTrangLoaiPhong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinhTrangLoaiPhong object.
        /// </summary>
        /// <param name="maTT">Initial value of the MaTT property.</param>
        public static TinhTrangLoaiPhong CreateTinhTrangLoaiPhong(global::System.Int32 maTT)
        {
            TinhTrangLoaiPhong tinhTrangLoaiPhong = new TinhTrangLoaiPhong();
            tinhTrangLoaiPhong.MaTT = maTT;
            return tinhTrangLoaiPhong;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaTT
        {
            get
            {
                return _MaTT;
            }
            set
            {
                if (_MaTT != value)
                {
                    OnMaTTChanging(value);
                    ReportPropertyChanging("MaTT");
                    _MaTT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaTT");
                    OnMaTTChanged();
                }
            }
        }
        private global::System.Int32 _MaTT;
        partial void OnMaTTChanging(global::System.Int32 value);
        partial void OnMaTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTT
        {
            get
            {
                return _TenTT;
            }
            set
            {
                OnTenTTChanging(value);
                ReportPropertyChanging("TenTT");
                _TenTT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenTT");
                OnTenTTChanged();
            }
        }
        private global::System.String _TenTT;
        partial void OnTenTTChanging(global::System.String value);
        partial void OnTenTTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_LoaiPhong_TinhTrangLoaiPhong", "LoaiPhong")]
        public EntityCollection<LoaiPhong> LoaiPhongs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "LoaiPhong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LoaiPhong>("QuanLyKhachSanModel.FK_LoaiPhong_TinhTrangLoaiPhong", "LoaiPhong", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="TinhTrangPhong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinhTrangPhong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinhTrangPhong object.
        /// </summary>
        /// <param name="maTTP">Initial value of the MaTTP property.</param>
        public static TinhTrangPhong CreateTinhTrangPhong(global::System.Int32 maTTP)
        {
            TinhTrangPhong tinhTrangPhong = new TinhTrangPhong();
            tinhTrangPhong.MaTTP = maTTP;
            return tinhTrangPhong;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaTTP
        {
            get
            {
                return _MaTTP;
            }
            set
            {
                if (_MaTTP != value)
                {
                    OnMaTTPChanging(value);
                    ReportPropertyChanging("MaTTP");
                    _MaTTP = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaTTP");
                    OnMaTTPChanged();
                }
            }
        }
        private global::System.Int32 _MaTTP;
        partial void OnMaTTPChanging(global::System.Int32 value);
        partial void OnMaTTPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTT
        {
            get
            {
                return _TenTT;
            }
            set
            {
                OnTenTTChanging(value);
                ReportPropertyChanging("TenTT");
                _TenTT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenTT");
                OnTenTTChanged();
            }
        }
        private global::System.String _TenTT;
        partial void OnTenTTChanging(global::System.String value);
        partial void OnTenTTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_Phong_TinhTrangPhong", "Phong")]
        public EntityCollection<Phong> Phongs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Phong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "Phong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Phong>("QuanLyKhachSanModel.FK_Phong_TinhTrangPhong", "Phong", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLyKhachSanModel", Name="TinhTrangPT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TinhTrangPT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TinhTrangPT object.
        /// </summary>
        /// <param name="maTT">Initial value of the MaTT property.</param>
        public static TinhTrangPT CreateTinhTrangPT(global::System.Int32 maTT)
        {
            TinhTrangPT tinhTrangPT = new TinhTrangPT();
            tinhTrangPT.MaTT = maTT;
            return tinhTrangPT;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaTT
        {
            get
            {
                return _MaTT;
            }
            set
            {
                if (_MaTT != value)
                {
                    OnMaTTChanging(value);
                    ReportPropertyChanging("MaTT");
                    _MaTT = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MaTT");
                    OnMaTTChanged();
                }
            }
        }
        private global::System.Int32 _MaTT;
        partial void OnMaTTChanging(global::System.Int32 value);
        partial void OnMaTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenTT
        {
            get
            {
                return _TenTT;
            }
            set
            {
                OnTenTTChanging(value);
                ReportPropertyChanging("TenTT");
                _TenTT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenTT");
                OnTenTTChanged();
            }
        }
        private global::System.String _TenTT;
        partial void OnTenTTChanging(global::System.String value);
        partial void OnTenTTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLyKhachSanModel", "FK_PhieuThue_TinhTrangPT", "PhieuThue")]
        public EntityCollection<PhieuThue> PhieuThues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "PhieuThue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhieuThue>("QuanLyKhachSanModel.FK_PhieuThue_TinhTrangPT", "PhieuThue", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
